using JorgeCostaMacia.Http.Domain;

namespace JorgeCostaMacia.Http.ProblemDetails.Domain;

/// <summary>
/// Represents the standardized schema for validation and domain errors,
/// used to provide consistent API error responses across the infrastructure.
/// </summary>
/// <remarks>
/// This model follows the <b>RFC 7807</b> (Problem Details for HTTP APIs) specification
/// while adding custom traceability and aggregate metadata.
/// </remarks>
public sealed record ProblemDetails : IResponseHttp
{
    /// <summary>
    /// A URI reference [RFC3986] that identifies the problem type.
    /// Defaults to "about:blank" if not present.
    /// </summary>
    public string? Type { get; init; }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    public string? Title { get; init; }

    /// <summary>
    /// The HTTP status code generated by the origin server.
    /// </summary>
    public int? Status { get; init; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string? Detail { get; init; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// </summary>
    public string? Instance { get; init; }

    /// <summary>
    /// The unique identifier of the current HTTP request, used for log correlation.
    /// </summary>
    public string? RequestId { get; init; }

    /// <summary>
    /// The activity trace identifier used for distributed tracing (W3C Trace Context).
    /// </summary>
    public string? TraceId { get; init; }

    /// <summary>
    /// The unique identifier of the server or container node that processed the request.
    /// Useful for identifying specific failing instances in scaled environments.
    /// </summary>
    public string? NodeId { get; init; }

    /// <summary>
    /// Unique identifier of this specific error occurrence, used for auditing
    /// and correlating this error with server-side logs.
    /// </summary>
    /// <remarks>
    /// Unlike <see cref="AggregateCode"/>, which is shared by every occurrence of the same
    /// error type, this value is unique to this single occurrence.
    /// Corresponds to <see cref="Exception.Domain.DomainException.AggregateId"/>.
    /// </remarks>
    public Guid? AggregateId { get; init; }

    /// <summary>
    /// Stable identifier of the error type (e.g. the GUID assigned to <c>UsuarioNotFound</c>),
    /// shared by every occurrence of that same error type, intended for programmatic handling
    /// by client applications.
    /// </summary>
    /// <remarks>
    /// Unlike <see cref="AggregateId"/>, which is unique per occurrence, this value is fixed
    /// per error type. Corresponds to <see cref="Exception.Domain.DomainException.AggregateCode"/>.
    /// </remarks>
    public Guid? AggregateCode { get; init; }

    /// <summary>
    /// The technical type name or full name of the exception that triggered this error response.
    /// </summary>
    /// <remarks>
    /// Corresponds to the <see cref="Exception.Domain.DomainException.AggregateType"/>.
    /// </remarks>
    public string? AggregateType { get; init; }

    /// <summary>
    /// A dictionary containing the validation failure details, where each key
    /// is a property name and the value is an array of error messages.
    /// </summary>
    public Dictionary<string, string[]>? Errors { get; init; }
}
