<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\..\src\JorgeCostaMacia.Http.MinimalApi.Versioning\JorgeCostaMacia.Http.MinimalApi.Versioning.csproj" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	</ItemGroup>

</Project>
