<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\JorgeCostaMacia.Http.Serilog\JorgeCostaMacia.Http.Serilog.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.TestHost" />
	</ItemGroup>

</Project>
